name: wiseclient
description: A http client based on Dio with extra features.
version: 1.0.0

environment:
  sdk: ^3.1.3

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  fresh_dio: ^0.4.1
  native_dio_adapter: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.21.0

flutter:
