name: wiseclient
description: A http client based on Dio with extra features.
version: 1.0.1

environment:
  sdk: ^3.1.3

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  fresh_dio: ^0.4.1
  native_dio_adapter: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.1
  test: ^1.24.9

flutter:
