name: wiseclient
description: A http client based on Dio with extra features.
version: 1.0.5+1
publish_to: https://f9f5-84-193-8-153.ngrok-free.app/

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  fresh_dio: ^0.4.1
  native_dio_adapter: ^1.3.0
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2

flutter:
