# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run linter and analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
      
      - run: flutter --version
      
      - name: Run flutter pub get
        uses: flutter pub get
      
      - name: Run build runner
        uses: dart pub run build_runner build -d

      - name: Verify formatting
        run: dart format . --line-length=200 --set-exit-if-changed

      - name: Analyze project source
        run: dart analyze
